name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  deploy-on-aliyun:
    # needs: build-and-deploy
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Setup git file
        env: 
          ACTIONS_DEPLOY_KEY: ${{ secrets.deploy_key }}
          USER: root
        run: |
          SSH_PATH="~/.ssh"
          mkdir -p $SSH_PATH
          touch "$SSH_PATH/known_hosts"
          echo "$ACTIONS_DEPLOY_KEY" > "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          echo "file addad"
      - name: Setup git excute
        env: 
          USER: root
          HOST: 47.106.96.91
          PACKAGE_NAME: blog
          HOME_PATH: /home
          DEVELOP_SH_PATH: /root/deploy_blog.sh
        run: |
          SSH_PATH="~/.ssh"
          eval $(ssh-agent)
          echo "$SSH_PATH/id_rsa"
          ssh-add "$SSH_PATH/id_rsa"
          ssh-keyscan -t rsa $HOST >> "$SSH_PATH/known_hosts"
          echo "go ssh"
          ssh "$USER@$HOST"
          sh "$DEVELOP_SH_PATH"
          logout
          
